inventario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.listar_productos, name='listar_productos'),  # Ruta URL base
    path('listar_productos/', views.listar_productos, name='listar_productos'),
    path('productos/', views.listar_productos, name='productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('inventario/', views.inventario, name='inventario'),

    # ... otras URLs ...
]

ipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls')),
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario/models.py
from django.db import models
from PIL import Image

class Producto(models.Model):
    producto = models.CharField(max_length=100, default='PEPELMA')
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=20, unique=True)
    stock = models.DecimalField(max_digits=10, decimal_places=2)
    unidad = models.CharField(max_length=10, default='M2')
    precio_distribuidor = models.DecimalField(max_digits=10, decimal_places=2)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    caja = models.PositiveIntegerField(default=1)
    presentacion = models.CharField(max_length=100, default='CAJAS x 2 M2')
    moneda = models.CharField(max_length=10, choices=[('USD', 'Dólar estadounidense'), ('SOL', 'Sol peruano')], default='USD')
    imagen = models.ImageField(upload_to='productos', default='images/default.jpg')
    imagen_instalada = models.ImageField(upload_to='productos', default='images/default.jpg')
    categoria = models.CharField(max_length=100, default='SIN CATEGORIA')
    en_oferta = models.BooleanField(default=False)
    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.imagen.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.imagen.path)

inventario/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

inventario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductoForm # Asegúrate de tener un formulario para editar el producto
from .models import Producto
from django.http import JsonResponse

def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listar_productos')
    else:
        form = ProductoForm()
    return render(request, 'agregar_producto.html', {'form': form})


def listar_productos(request):
    productos = Producto.objects.order_by('id')
    categorias = Producto.objects.values('categoria').distinct()
    return render(request, 'listar_productos.html', {'productos': productos, 'categorias': categorias})


def editar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('listar_productos')  # Redirige a la página de lista de productos o a donde desees
    else:
        form = ProductoForm(instance=producto)

    return render(request, 'editar_producto.html', {'form': form, 'producto': producto})


def inventario(request):
    return render(request, 'base.html')

inventario/templates/agregar_producto.html
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Producto</title>
</head>
<body>
    <h1>Agregar Producto</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Producto</button>
    </form>
</body>
</html>

inventario/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Productos</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
<style>    

    /* Estilos para el header */
    #header {
        background-color: #3498db;
        color: #fff;
        padding: 20px;
    }

    .company-info {
        display: flex;
        align-items: center;
        justify-content: space-between;; /* Alinea el título a la izquierda y el logo a la derecha */
        
    }

    h1 {
        margin: 0; /* Elimina el margen predeterminado del h1 para evitar espacio adicional */
    }

    .logo {
        margin-right: 60%; /* Ajusta el margen derecho según tus preferencias */
    }

    /* Estilos para el sidebar */
    #sidebar {
        background-color: #333;
        color: #fff;
        padding: 50px;
        min-height: 100vh;
    }
    
    #sidebar ul {
        list-style: none;
        padding: 0;
    }
    
    #sidebar li {
        margin-bottom: 10px;
    }
    
    #sidebar a {
        color: #fff;
        text-decoration: none;
    }
    
    /* Estilos para el contenido principal */
    #content {
        background-color: #f2f2f2;
        padding: 20px;
    }
    
    /* Estilos para el footer */
    #footer {
        background-color: #3498db;
        color: #fff;
        padding: 10px;
        text-align: center;
    }

    

</style>
<body>
    <!-- Encabezado -->
    <div id="header">
        <div class="company-info">
            <img src="/media/images/IPE.jpg" alt="Logo de la Compañía" width="100" class="logo">
            <h1>Inversiones Punta del Este S.A </h1>
        </div>
    </div>

    <!-- Contenedor principal -->
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-2" id="sidebar">
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Lista de Productos</a></li>
                    <li><a href="#">Agregar Producto</a></li>
                    <li><a href="#">Categorías</a></li>
                    <li><a href="#">Inventarios</a></li>
                    <li><a href="#">Reportes</a></li>
                </ul>
            </div>

            <!-- Contenido principal -->
            <div class="col-md-9" id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Pie de página -->
    <div id="footer">
        <div class="social-media">
            <a href="#">Facebook</a>
            <a href="#">Twitter</a>
            <a href="#">Instagram</a>
        </div>
        <p>&copy; {{ ano_actual }} Data Retail Solutions. Todos los derechos reservados.</p>
    </div>
</body>
</html>

inventario/templates/editar_producto.html
<!DOCTYPE html>
<!-- En tu archivo base.html o cualquier plantilla base que uses -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

<html>
<head>
    <title>Editar Producto</title>
</head>
<body>
    <h1>Editar Producto</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar Cambios">
    </form>
</body>
</html>

inventario/templates/footer.html
<!-- footer.html -->
<div id="footer">
    <div class="social-media">
        <a href="#">Facebook</a>
        <a href="#">Twitter</a>
        <a href="#">Instagram</a>
    </div>
    <p>&copy; {{ año_actual }} Inversiones Punta del Este. Todos los derechos reservados.</p>
</div>

inventario/templates/header.html
<!-- header.html -->
<div id="header">
    <div class="company-info">
        <h1>Nombre de la Compañía</h1>
        <img src="ruta/a/tu/logo.png" alt="Logo de la Compañía" width="100">
    </div>
</div>

inventario/templates/listar_productos.html
<!-- listar_productos.html -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
{% extends "base.html" %}

{% block content %}
    <!-- Contenido específico de la página Lista de Productos -->
    <h1>Lista de Productos</h1>
    <div style="overflow-x: auto;">
        <table border="1" class="table table-bordered table-striped">
            <!-- Contenido de la tabla de productos -->
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Imagen</th>
                    <th>Imagen Instalada</th>
                    <th>Nombre</th>
                    <th>Código</th>
                    <th>Stock</th>
                    <th>Unidad</th>
                    <th>Cajas</th>
                    <th>Presentación</th>
                    <th>Precio Distribuidor</th>
                    <th>Precio Venta</th>
                    <th>Moneda</th>
                    <th>En Oferta</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for categoria in categorias %}
                    <tr>
                        <th colspan="12">{{ categoria.categoria }}</th>
                    </tr>
                    {% for producto in productos %}
                        {% if producto.categoria == categoria.categoria %}
                            <tr>
                            <td>{{ producto.producto }}</td>
                            <td><img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" width="100" onclick="showImage('{{ producto.imagen.url }}')"></td>
                            <td><img src="{{ producto.imagen_instalada.url }}" alt="{{ producto.nombre }}" width="100"></td>
                            <td>{{ producto.nombre }}</td>
                            <td>{{ producto.codigo }}</td>
                            <td>{{ producto.stock }}</td>
                            <td>{{ producto.unidad }}</td>
                            <td>{{ producto.caja }}</td>
                            <td>{{ producto.presentacion }}</td>
                            <td>${{ producto.precio_distribuidor }}</td>
                            <td>${{ producto.precio_venta }}</td>
                            <td>{{ producto.get_moneda_display }}</td>
                            <td>
                                {% if producto.en_oferta %}
                                    Si <i class="bi bi-check"></i>
                                {% else %}
                                    No
                                {% endif %}
                            </td>
                            <td><a href="{% url 'editar_producto' producto.id %}">Editar</a></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <style>
        table {
          width: 50%;
          margin: 0 auto;
          border-collapse: collapse;
        }
    
        table, th, td {
          border: 1px solid #ccc;
        }
    
        th, td {
          padding: 10px;
          text-align: center;
        }
    
        .modal {
          display: none;
          position: fixed;
          z-index: 1;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
          width: 15%;
          height: 15%;
          overflow: auto;
          background-color: rgba(0, 0, 0, 0.9);
        }
    
        .modal-content {
          display: block;
          margin: 0 auto;
          max-width: 100%;
          max-height: 100%;
          display: flex;
          justify-content: center;
          align-items: center;
        }
    
        .close {
          position: absolute;
          top: 10px;
          right: 10px;
          color: #fff;
          font-size: 20px;
          font-weight: bold;
          cursor: pointer;
        }
    </style>
    
    <div id="myModal" class="modal" onclick="closeModal()">
        <span class="close" onclick="closeModal()">&times;</span>
        <img class="modal-content" id="img01">
    </div>
    
    <script>
        function openModal() {
            document.getElementById('myModal').style.display = 'block';
        }
    
        function closeModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    
        function showImage(imageSrc) {
            var modal = document.getElementById('myModal');
            var modalImg = document.getElementById('img01');
            modal.style.display = 'block';
            modalImg.src = imageSrc;
        }
    </script>
    
{% endblock %}

inventario/templates/listar_productos_old.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Productos</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
<body>
    <!-- Sidebar -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <!-- Aquí coloca el contenido de tu sidebar, como menús o enlaces -->
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-3">
                            {% include 'sidebar.html' %}
                        </div>
                        <div class="col-md-9">
                            <!-- Encabezado, tabla y pie de página aquí -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <!-- Encabezado -->
                {% include 'header.html' %}
                <h1>Lista de Productos</h1>
                <div style="overflow-x: auto;">
                    <table border="1" class="table table-bordered table-striped">
                        <!-- Contenido de la tabla -->
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Imagen</th>
                                <th>Imagen Instalada</th>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Stock</th>
                                <th>Unidad</th>
                                <th>Cajas</th>
                                <th>Presentación</th>
                                <th>Precio Distribuidor</th>
                                <th>Precio Venta</th>
                                <th>Moneda</th>
                                <th>En Oferta</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for categoria in categorias %}
                                <tr>
                                    <th colspan="12">{{ categoria.categoria }}</th>
                                </tr>
                                {% for producto in productos %}
                                    {% if producto.categoria == categoria.categoria %}
                                        <tr>
                                        <td>{{ producto.producto }}</td>
                                        <td><img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" width="100" onclick="showImage('{{ producto.imagen.url }}')"></td>
                                        <td><img src="{{ producto.imagen_instalada.url }}" alt="{{ producto.nombre }}" width="100"></td>
                                        <td>{{ producto.nombre }}</td>
                                        <td>{{ producto.codigo }}</td>
                                        <td>{{ producto.stock }}</td>
                                        <td>{{ producto.unidad }}</td>
                                        <td>{{ producto.caja }}</td>
                                        <td>{{ producto.presentacion }}</td>
                                        <td>${{ producto.precio_distribuidor }}</td>
                                        <td>${{ producto.precio_venta }}</td>
                                        <td>{{ producto.get_moneda_display }}</td>
                                        <td>
                                            {% if producto.en_oferta %}
                                                Si <i class="bi bi-check"></i>
                                            {% else %}
                                                No
                                            {% endif %}
                                        </td>
                                        <td><a href="{% url 'editar_producto' producto.id %}">Editar</a></td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- Pie de página -->
                {% include 'footer.html' %}
            </div>
        </div>
    </div>
</body>
</html>

<style>
    table {
      width: 50%;
      margin: 0 auto;
      border-collapse: collapse;
    }

    table, th, td {
      border: 1px solid #ccc;
    }

    th, td {
      padding: 10px;
      text-align: center;
    }

    .modal {
      display: none;
      position: fixed;
      z-index: 1;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
      width: 15%;
      height: 15%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.9);
    }

    .modal-content {
      display: block;
      margin: 0 auto;
      max-width: 100%;
      max-height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .close {
      position: absolute;
      top: 10px;
      right: 10px;
      color: #fff;
      font-size: 20px;
      font-weight: bold;
      cursor: pointer;
    }
</style>

<div id="myModal" class="modal" onclick="closeModal()">
    <span class="close" onclick="closeModal()">&times;</span>
    <img class="modal-content" id="img01">
</div>

<script>
    function openModal() {
        document.getElementById('myModal').style.display = 'block';
    }

    function closeModal() {
        document.getElementById('myModal').style.display = 'none';
    }

    function showImage(imageSrc) {
        var modal = document.getElementById('myModal');
        var modalImg = document.getElementById('img01');
        modal.style.display = 'block';
        modalImg.src = imageSrc;
    }
</script>

inventario/templates/sidebar.html
<!-- sidebar.html -->
<div class="sidebar">
    <ul class="list-group">
        <li class="list-group-item"><a href="#">Inicio</a></li>
        <li class="list-group-item"><a href="#">Lista de Productos</a></li>
        <li class="list-group-item"><a href="#">Agregar Producto</a></li>
        <li class="list-group-item"><a href="#">Categorías</a></li>
        <li class="list-group-item"><a href="#">Inventarios</a></li>
        <li class="list-group-item"><a href="#">Reportes</a></li>
    </ul>
</div>